name: DEPLOY PREVIEW CHANNEL

on:
# Только ручной деплой в продакшен по кнопке:
  workflow_dispatch:
#  push:
#    branches:
#      - 'master'
#      - 'develop'
#      - 'release/**'
#    paths:
#      - '**.dart'
#  pull_request:
#    branches:
#      - 'master'
#      - 'develop'
#      - 'release/**'
#    paths:
#      - '**.dart'

jobs:
  # Build
  build:
    #if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    name: 'Build preview'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: plugfox/flutter:stable-web
      #image: plugfox/flutter:2.10.3-web
      options: --user root
    steps:
      - name: 🚂 Get latest code
        uses: actions/checkout@v2

      - name: 🚃 Cache pub modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pub-modules
        with:
          path: |
            /var/tmp/.pub_cache/
          key: ${{ runner.os }}-dart

      - name: 🌐 Build
        run: |
          apk add make
          make build

      - name: 📁 Upload web build result
        uses: actions/upload-artifact@v2
        with:
          name: web-preview
          retention-days: 1
          path: |
            public/
              
  # Deploy on preview / staging channel
  deploy:
    name: 'Deploy preview'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: build
    env:
      working-directory: ./public
    steps:
      - name: 📦 Download result for web build job
        uses: actions/download-artifact@v2
        with:
          name: web-preview
          path: public

      - name: 📥 Extract web artifact
        working-directory: ${{ env.working-directory }}
        run: |
          ls -al
      
      - name: 🔥 Deploy to Firebase preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ${{ env.working-directory }}
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXAMPLE_PLUGFOX_DEV }}'
          expires: 7d
          channelId: stg
          projectId: example-plugfox-dev
          target: example-plugfox-dev
